
@baseUrl = http://localhost:3333
#health check
GET {{baseUrl}}/health


###

# @name getRooms
GET {{baseUrl}}/rooms

###

# @name createRoom
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
  "name": "test room",
  "description": "this is a test room"
}


###

@roomId = {{createRoom.response.body.$.roomId}}

###

# @name getRoomQuestions

GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# @name createQuestion
POST {{baseUrl}}/rooms/{{roomId}}/questions
Accept: application/json
Content-Type: application/json

{
  "question": "what is the capital of France?"
}
